version: 0.2
phases:
 install:
   commands:
     - wget -qO- https://deb.nodesource.com/setup_15.x | sudo -E bash -
     - sudo apt-get -y update
     - sudo apt-get -y upgrade
     - sudo apt-get install -y nodejs
     - sudo apt-get install -y build-essential
     - npm install
     - npm install react-scripts@latest
       #     - npm install terser
 build:
   commands:
     - npm run build
 post_build:
   commands:
     - aws s3 sync --delete build/ "s3://colorblind-message-encrypter/"

