version: 0.2
phases:
 install:
   runtime-versions:
     nodejs: latest
   commands:
     - npm install
     - npm install react-scripts@latest
 build:
   commands:
     - npm run build
artifacts:
  files:
    - build/*

